data:
  data_path: ../data
  chargeback_file: dispute_chargeback_20250612.csv
  ok_transactions_file: ok_transactions_20250612.csv
  temporal_split_days: 30
  historical_context_days: 90
  max_edges_per_entity: 100
  time_window_hours: 24
  min_edge_frequency: 2
model:
  hidden_dim: 256
  n_layers: 2
  heads:
  - 4
  - 4
  dropout:
  - 0.2
  - 0.1
  - 0.1
  activation: prelu
  learning_rate: 0.001
  weight_decay: 0.0001
  batch_size: 512
  epochs: 50
  patience: 10
  use_class_weights: true
  device: auto
features:
  extract_hour: true
  extract_day_of_week: true
  extract_weekend: true
  extract_night_hours: true
  log_transform_amount: true
  round_amount_detection: true
  high_amount_threshold: 0.95
  neighborhood_hops:
  - 1
  - 2
  compute_fraud_rates: true
  compute_velocity_features: true
  handle_missing_categories: true
  max_categories_per_feature: 1000
business:
  average_chargeback_cost: 67.66
  average_transaction_value: 11.04
  false_positive_review_cost: 11.38
  high_risk_threshold: 0.7
  medium_risk_threshold: 0.4
  low_risk_threshold: 0.2
  batch_prediction_hours: 24
  max_batch_size: 10000
  max_daily_reviews: 1000
  target_precision: 0.4
evaluation:
  calculate_auc: true
  calculate_precision_recall: true
  calculate_business_metrics: true
  threshold_range:
  - 0.1
  - 0.9
  threshold_step: 0.1
  generate_plots: true
  save_predictions: true
  top_k_alerts: 100
production:
  model_save_path: models/fraud_rgtan_model.pt
  backup_models: true
  max_model_versions: 5
  enable_performance_monitoring: true
  alert_on_performance_drop: true
  performance_threshold: 0.75
  retrain_frequency_days: 30
  min_new_fraud_cases: 100
  performance_degradation_threshold: 0.05
  batch_processing_enabled: true
  batch_schedule: 0 1 * * *
  api_timeout_seconds: 30
  max_concurrent_requests: 100
logging:
  level: INFO
  log_file: logs/fraud_detection.log
  max_log_size_mb: 100
  backup_count: 5
  log_predictions: true
  log_feature_importance: true
  log_model_performance: true
  log_business_metrics: true
security:
  hash_sensitive_fields: true
  mask_card_numbers: true
  encrypt_personal_data: false
  model_encryption: false
  feature_obfuscation: false
  require_authentication: false
  allowed_ip_ranges: []
environments:
  development:
    data:
      data_path: ../data
    model:
      epochs: 10
      batch_size: 256
    logging:
      level: DEBUG
  staging:
    data:
      data_path: /staging/data
    production:
      enable_performance_monitoring: true
    logging:
      level: INFO
  production:
    data:
      data_path: /production/data
    model:
      batch_size: 1024
    production:
      enable_performance_monitoring: true
      alert_on_performance_drop: true
    security:
      hash_sensitive_fields: true
      require_authentication: true
    logging:
      level: WARNING
integrations:
  database:
    enabled: false
    connection_string: ''
    transaction_table: transactions
    fraud_labels_table: fraud_labels
  message_queue:
    enabled: false
    provider: kafka
    topic: fraud_alerts
  apis:
    risk_scoring_service:
      enabled: false
      endpoint: ''
      timeout: 5
    notification_service:
      enabled: false
      endpoint: ''
  storage:
    provider: s3
    bucket: fraud-detection-models
    region: us-east-1
performance:
  max_memory_usage_gb: 8
  enable_memory_mapping: true
  num_workers: 4
  use_multiprocessing: true
  enable_feature_caching: true
  cache_size_mb: 1024
  cache_ttl_hours: 24
  gpu_memory_fraction: 0.8
  mixed_precision: false
experimental:
  use_graph_attention: false
  dynamic_thresholds: false
  ensemble_models: false
  automatic_feature_selection: false
  deep_feature_synthesis: false
  generate_explanations: false
  feature_importance_tracking: false
calculated_metrics:
  last_updated: '2025-06-10T23:14:15.962793'
  data_source: dispute_chargeback_20250606.csv and ok_transactions_20250606.csv
  fraud_rate: 0.0123
  chargeback_statistics:
    average_amount: 16.3
    median_amount: 3.99
    p95_amount: 49.99
  cost_breakdown:
    chargeback:
      transaction_amount: 16.299692013331686
      fees_and_overhead: 45.65198768053327
      lost_value: 5.7048922046660895
    review:
      avg_review_time_minutes: 15
      analyst_hourly_rate: 35.0
      base_review_cost: 8.75
      overhead_multiplier: 1.3
      total_review_cost: 11.375
