# RGTAN Fraud Detection Configuration
# Configuration for chargeback and fraud prevention system

# Data Configuration
data:
  # Paths to input data files
  data_path: "../data"
  chargeback_file: "dispute_chargeback_20250606.csv"
  ok_transactions_file: "ok_transactions_20250606.csv"
  
  # Preprocessing settings
  temporal_split_days: 30  # Days for test set
  historical_context_days: 90  # Days of historical data for graph context
  
  # Graph construction parameters
  max_edges_per_entity: 100
  time_window_hours: 24
  min_edge_frequency: 2

# Model Configuration
model:
  # Architecture parameters
  hidden_dim: 256
  n_layers: 2
  heads: [4, 4]  # Attention heads per layer
  dropout: [0.2, 0.1, 0.1]  # Input, hidden, output dropout
  activation: "prelu"
  
  # Training parameters
  learning_rate: 0.001
  weight_decay: 0.0001
  batch_size: 512
  epochs: 50
  patience: 10  # Early stopping patience
  
  # Class balancing
  use_class_weights: true
  
  # Device settings
  device: "auto"  # "auto", "cpu", "cuda"

# Feature Engineering
features:
  # Temporal features
  extract_hour: true
  extract_day_of_week: true
  extract_weekend: true
  extract_night_hours: true
  
  # Amount features
  log_transform_amount: true
  round_amount_detection: true
  high_amount_threshold: 0.95  # Percentile
  
  # Graph features
  neighborhood_hops: [1, 2]
  compute_fraud_rates: true
  compute_velocity_features: true
  
  # Categorical encoding
  handle_missing_categories: true
  max_categories_per_feature: 1000

# Business Rules
business:
  # Cost parameters for ROI calculation
  average_chargeback_cost: 50.0
  average_transaction_value: 75.0
  false_positive_review_cost: 10.0
  
  # Alert thresholds
  high_risk_threshold: 0.7
  medium_risk_threshold: 0.4
  low_risk_threshold: 0.2
  
  # Batch processing
  batch_prediction_hours: 24
  max_batch_size: 10000
  
  # Review capacity
  max_daily_reviews: 1000
  target_precision: 0.4  # 40% of flagged transactions should be fraud

# Evaluation Settings
evaluation:
  # Metrics to calculate
  calculate_auc: true
  calculate_precision_recall: true
  calculate_business_metrics: true
  
  # Threshold analysis
  threshold_range: [0.1, 0.9]
  threshold_step: 0.1
  
  # Reporting
  generate_plots: true
  save_predictions: true
  top_k_alerts: 100

# Production Settings
production:
  # Model persistence
  model_save_path: "models/fraud_rgtan_model.pt"
  backup_models: true
  max_model_versions: 5
  
  # Monitoring
  enable_performance_monitoring: true
  alert_on_performance_drop: true
  performance_threshold: 0.75  # Minimum AUC
  
  # Retraining triggers
  retrain_frequency_days: 30
  min_new_fraud_cases: 100  # Minimum new fraud cases before retraining
  performance_degradation_threshold: 0.05  # AUC drop that triggers retraining
  
  # Batch processing schedule
  batch_processing_enabled: true
  batch_schedule: "0 1 * * *"  # Daily at 1 AM (cron format)
  
  # API settings
  api_timeout_seconds: 30
  max_concurrent_requests: 100

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_file: "logs/fraud_detection.log"
  max_log_size_mb: 100
  backup_count: 5
  
  # What to log
  log_predictions: true
  log_feature_importance: true
  log_model_performance: true
  log_business_metrics: true

# Security Settings
security:
  # Data privacy
  hash_sensitive_fields: true
  mask_card_numbers: true
  encrypt_personal_data: false
  
  # Model protection
  model_encryption: false
  feature_obfuscation: false
  
  # Access control
  require_authentication: false
  allowed_ip_ranges: []

# Environment Specific Overrides
environments:
  development:
    data:
      data_path: "../data"
    model:
      epochs: 10
      batch_size: 256
    logging:
      level: "DEBUG"
  
  staging:
    data:
      data_path: "/staging/data"
    production:
      enable_performance_monitoring: true
    logging:
      level: "INFO"
  
  production:
    data:
      data_path: "/production/data"
    model:
      batch_size: 1024
    production:
      enable_performance_monitoring: true
      alert_on_performance_drop: true
    security:
      hash_sensitive_fields: true
      require_authentication: true
    logging:
      level: "WARNING"

# Integration Settings
integrations:
  # Database connections
  database:
    enabled: false
    connection_string: ""
    transaction_table: "transactions"
    fraud_labels_table: "fraud_labels"
  
  # Message queue
  message_queue:
    enabled: false
    provider: "kafka"  # kafka, rabbitmq, sqs
    topic: "fraud_alerts"
    
  # External APIs
  apis:
    risk_scoring_service:
      enabled: false
      endpoint: ""
      timeout: 5
    
    notification_service:
      enabled: false
      endpoint: ""
      
  # Cloud storage
  storage:
    provider: "s3"  # s3, gcs, azure
    bucket: "fraud-detection-models"
    region: "us-east-1"

# Performance Tuning
performance:
  # Memory management
  max_memory_usage_gb: 8
  enable_memory_mapping: true
  
  # Parallel processing
  num_workers: 4
  use_multiprocessing: true
  
  # Caching
  enable_feature_caching: true
  cache_size_mb: 1024
  cache_ttl_hours: 24
  
  # GPU settings
  gpu_memory_fraction: 0.8
  mixed_precision: false

# Experimental Features
experimental:
  # Advanced model features
  use_graph_attention: false
  dynamic_thresholds: false
  ensemble_models: false
  
  # Feature engineering
  automatic_feature_selection: false
  deep_feature_synthesis: false
  
  # Interpretability
  generate_explanations: false
  feature_importance_tracking: false